- name: turn off git colorization
  become_user: "{{ helen_username }}"
  git_config:
    name: color.ui
    scope: global
    value: false
- name: don't colorize ansible
  become_user: "{{ helen_username }}"
  blockinfile:
    path: ~/.ansible.cfg
    create: yes
    block: |
      [defaults]
      nocolor=true
    